name: dfs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install build-essential nasm qemu qemu-utils dosfstools
      - run: make build/disk.img
      - run: tools/fatinfo.py build/disk.img
